version: '3.4'

services:

  seq:
    image: datalust/seq:latest
    environment:
        ACCEPT_EULA: "Y"
    ports:
        - 6341:80
    volumes:
        - data:/usr/share/seq/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    depends_on:
      - kafka
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    environment:
        SA_PASSWORD: "Pass@word"
        ACCEPT_EULA: "Y"
    depends_on:
      - kafka
    ports:
        - "6001:1433"
    volumes:
      - data:/var/opt/mssql/data

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  wilmerflorez.api:
    image: ${DOCKER_REGISTRY-}wilmerflorezapi
    container_name: wilmer-florez-dev
    environment:
        SQL_SERVER_CONNECTION: "Server=sqldata; Database=WilmerFlorezDb; User=sa; Password=Pass@word;"
        SEQURL: "http://seq"
    ports:
        - "6200:80"
    build:
      context: .
      dockerfile: WilmerFlorez.Api/Dockerfile

volumes:
  data:
  elasticsearch-data:
