apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    name: app
    type: netapi
spec:
  containers:
  - name: app-api
    image: wflorez/wilmerflorezapi:latest
    ports:
      - containerPort: 5000
    env:
      - name: ConnectionStrings__SQLServerConnection
        value: Data Source=mssql-service; Initial Catalog=n5DB; User Id=sa;password=Pass@word
